Add `roave/security-advisories` as suggested dependency
guardrailsio/awesome-php-security pull request #4
Opened 2018-12-17 19:43 UTC by Ocramius

It is a very simple addition that leads to the exclusion of vulnerable dependencies
directly when `composer update` is running

2018-12-17 20:12 UTC, paragonie-scott commented
This was one of my suggestions in #3 :)

2018-12-17 20:12 UTC, Ocramius commented
@paragonie-scott sorry, didn't see it before ^_^

2018-12-18 03:25 UTC, streichsbaer requested changes
Thanks for the contribution @Ocramius. 
Please just remove the backticks as per the comment below, then it's good to be merged.

2018-12-18 03:25 UTC, streichsbaer commented on README.md
> +- [`roave/security-advisories`](https://github.com/Roave/SecurityAdvisories) - Add this dependency to disallow known/vulnerable installation of packages directly through `composer update`
Please remove the backticks in the link name, so it's the same format as the others.

2018-12-18 12:44 UTC, Ocramius commented on README.md
> +- [`roave/security-advisories`](https://github.com/Roave/SecurityAdvisories) - Add this dependency to disallow known/vulnerable installation of packages directly through `composer update`
@streichsbaer done :+1:

2018-12-20 04:53 UTC, streichsbaer approved these changes

2018-12-20 04:53 UTC, merged